name: Build Test Deploy
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
    - uses: actions/checkout@v4
    - name: Use Node.js latest version 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Build the application
      run: npm install
    - name: Run Unit tests
      run: npm run test
    - name: Display softuni username
      run: echo "Orion87"
    
