name: Build Test Deploy
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-unit-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Use Node.js latest version 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Build the application
      run: npm install
    - name: Run Unit tests
      run: npm run test:unit
    - name: Display softuni username
      run: echo "Orion87"
  run-ui-tests:
    runs-on: ubuntu-latest
    needs: build-unit-test
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Use Node.js latest version 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Build the application   
      run: npm install
    - name: Install Playwright
      run: npx playwright install
    - name: Start application
      run: npm run start &
    - name: Run UI Tests
      run: npm run test:ui
  deploy:
    needs: run-ui-tests
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}
